import { Roboto } from "next/font/google"

import "./globals.css"
import Header from "@/components/Layout/Header"
import Footer from "@/components/Layout/Footer"

const roboto = Roboto({
   weight: ["100", "300", "400", "500", "700", "900"],
   style: ["normal", "italic"],
   subsets: ["latin"],
   display: "swap",
})

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={roboto.className}>
            <Header />
            <main>{children}</main>
            <Footer />
         </body>
      </html>
   )
}
